stages:
  preprocess_cytosis:
    cmd: python src/preprocess_cytosis.py --input data/processed/model_1/cleaned_data.csv --outdir data/processed_cytosis
    deps:
      - src/preprocess_cytosis.py
      - data/processed/model_1/cleaned_data.csv
    outs:
      - data/processed_cytosis

  train_cytosis:
    cmd: python src/train_cytosis.py --datadir data/processed_cytosis --params params.yaml --modeldir models/cytosis --metrics metrics_cytosis.json
    deps:
      - src/train_cytosis.py
      - data/processed_cytosis
      - params.yaml
    outs:
      - models/cytosis
    metrics:
      - metrics_cytosis.json
      
  preprocess_images:
    cmd: python src/preprocess_images.py --params params.yaml
    deps:
      - src/preprocess_images.py
      - data/raw/model_2/train
      - data/raw/model_2/val
      - data/raw/model_2/test
    outs:
      - data/processed/image_data  # could store TFRecords or numpy arrays
